### ISSUE TITLE
rdkmaster.com 域名访问 http://rdkmaster.com/demo/time/basic 的时候，报错，所内域名访问则正常

### ISSUE THREAD

**Issue by rdkmaster** [rdkmaster/jigsaw#66]
```
ERROR Error: Uncaught (in promise): TypeError: Object.setPrototypeOf called on null or undefined
TypeError: Object.setPrototypeOf called on null or undefined
    at setPrototypeOf (native)
    at webpackJsonp.506.__extends (http://rdkmaster.com/2.chunk.js:4166:9)
    at http://rdkmaster.com/2.chunk.js:4187:5
    at Object.506 (http://rdkmaster.com/2.chunk.js:4669:2)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at Object.559 (http://rdkmaster.com/2.chunk.js:5305:64)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at Object.434 (http://rdkmaster.com/2.chunk.js:75:84)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at http://rdkmaster.com/main.bundle.js:120:10
    at setPrototypeOf (native)
    at webpackJsonp.506.__extends (http://rdkmaster.com/2.chunk.js:4166:9)
    at http://rdkmaster.com/2.chunk.js:4187:5
    at Object.506 (http://rdkmaster.com/2.chunk.js:4669:2)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at Object.559 (http://rdkmaster.com/2.chunk.js:5305:64)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at Object.434 (http://rdkmaster.com/2.chunk.js:75:84)
    at __webpack_require__ (http://rdkmaster.com/inline.bundle.js:53:30)
    at http://rdkmaster.com/main.bundle.js:120:10
    at resolvePromise (http://rdkmaster.com/polyfills.bundle.js:6216:31)
    at resolvePromise (http://rdkmaster.com/polyfills.bundle.js:6187:17)
    at http://rdkmaster.com/polyfills.bundle.js:6264:17
    at ZoneDelegate.invokeTask (http://rdkmaster.com/polyfills.bundle.js:5870:31)
    at Object.onInvokeTask (http://rdkmaster.com/vendor.bundle.js:4285:37)
    at ZoneDelegate.invokeTask (http://rdkmaster.com/polyfills.bundle.js:5869:36)
    at Zone.runTask (http://rdkmaster.com/polyfills.bundle.js:5637:47)
    at drainMicroTaskQueue (http://rdkmaster.com/polyfills.bundle.js:6030:35)
```

**Comment by rdkmaster** [comment]
see #64 @damoqiongqiu
